name: Publish Docker Images to YCR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $IMAGE_TAG

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpt7o7msj0kv25nq2l7
          CR_REPO: flatris
        uses: docker/build-push-action@v6
        with:
          context: ./apps/flatris
          file: ./apps/flatris/Dockerfile
          push: true
          tags: cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:${{ env.IMAGE_TAG }}, cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:latest
