apiVersion: v1
kind: Namespace
metadata:
  name: flatris
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatris
  namespace: flatris
  labels:
    app: flatris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatris
  template:
    metadata:
      labels:
        app: flatris
    spec:
      containers:
      - image: cr.yandex/crpt7o7msj0kv25nq2l7/flatris
        name: flatris
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flatris
  namespace: flatris
  labels:
    app: flatris
spec:
  ports:
  - name: flatris
    port: 3000
  selector:
    app: flatris
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: flatris
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: "nginx"
  rules:
  - host: flatris.tasenko.ru
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
    - secretName: letsencrypt-prod
      hosts:
        - flatris.tasenko.ru
